name: ๐ ุชูุฑูุฑ ุฎุทุฃ
description: ุงูุฅุจูุงุบ ุนู ุฎุทุฃ ุฃู ุณููู ุบูุฑ ูุชููุน
title: "[ุฎุทุฃ]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ุดูุฑุงู ูู ุนูู ุฃุฎุฐ ุงูููุช ููุฅุจูุงุบ ุนู ุฎุทุฃ! ูุฑุฌู ููุก ุงููููุฐุฌ ุฃุฏูุงู ููุณุงุนุฏุชูุง ูู ููู ูุฅุนุงุฏุฉ ุฅูุชุงุฌ ุงููุดููุฉ.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: ุงููุชุทูุจุงุช ุงููุณุจูุฉ
      description: ูุฑุฌู ุชุฃููุฏ ูุง ููู ูุจู ุชูุฏูู ุชูุฑูุฑ ุงูุฎุทุฃ
      options:
        - label: ุจุญุซุช ุนู ุงููุถุงูุง ุงูููุฌูุฏุฉ ุงูุชู ูุฏ ุชููู ูุฑุชุจุทุฉ ุจูุฐุง ุงูุฎุทุฃ
          required: true
        - label: ุฑุงุฌุนุช ุงูุชูุซูู ูุงูุฃุณุฆูุฉ ุงูุดุงุฆุนุฉ
          required: true
        - label: ุฃุณุชุฎุฏู ุฅุตุฏุงุฑุงู ูุฏุนููุงู ูู ุงูููุชุจุฉ
          required: true

  - type: textarea
    id: description
    attributes:
      label: ูุตู ุงูุฎุทุฃ
      description: ูุตู ูุงุถุญ ูููุชุถุจ ููุง ูู ุงูุฎุทุฃ
      placeholder: "ูุซุงู: ุญุณุงุจ ููุงููุช ุงูุตูุงุฉ ูุนูุฏ ููุช ูุฌุฑ ุบูุฑ ุตุญูุญ ููุฅุญุฏุงุซูุงุช..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: ุฎุทูุงุช ุฅุนุงุฏุฉ ุงูุฅูุชุงุฌ
      description: ุฎุทูุงุช ููุตูุฉ ูุฅุนุงุฏุฉ ุฅูุชุงุฌ ุงูุณููู
      placeholder: |
        1. ุฃูุดุฆ ูุณุฎุฉ SDK ุจุงูุฅุญุฏุงุซูุงุช...
        2. ุงุถุจุท ุงูุฎูุงุฑุงุช ุนูู...
        3. ุงุณุชุฏุน ุทุฑููุฉ getTimes()
        4. ูุงุญุธ ุงููุชูุฌุฉ ุบูุฑ ุงูุตุญูุญุฉ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: ุงูุณููู ุงููุชููุน
      description: ูุงุฐุง ูุฌุจ ุฃู ูุญุฏุซ ุจุฏูุงู ูู ุฐููุ
      placeholder: "ุชููุนุช ุฃู ูููู ููุช ุงููุฌุฑ 05:30 ุจูุงุกู ุนูู..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ุงูุณููู ุงููุนูู
      description: ูุงุฐุง ุญุฏุซ ูุนููุงูุ
      placeholder: "ุนุงุฏ ููุช ุงููุฌุฑ 04:15 ุจุฏูุงู ูู 05:30 ุงููุชููุน"
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: ุนููุฉ ุงูููุฏ
      description: ุนููุฉ ููุฏ ุจุณูุทุฉ ุชูุถุญ ุงููุดููุฉ
      render: typescript
      placeholder: |
        import { PrayerTimesSDK } from 'prayer-times-calculation';

        const sdk = new PrayerTimesSDK(
          24.7136, // ุฎุท ุงูุนุฑุถ
          46.6753, // ุฎุท ุงูุทูู
          new Date('2025-01-19'),
          3, // ุงูููุทูุฉ ุงูุฒูููุฉ
          {
            method: 'MWL',
            asrJurisdiction: 'Standard'
          }
        );

        const times = sdk.getTimes();
        console.log(times); // ูุธูุฑ ูุชูุฌุฉ ุบูุฑ ุตุญูุญุฉ
    validations:
      required: true

  - type: dropdown
    id: environment-sdk
    attributes:
      label: ุฅุตุฏุงุฑ ุงูููุชุจุฉ
      description: ุฃู ุฅุตุฏุงุฑ ูู ุงูููุชุจุฉ ุชุณุชุฎุฏูุ
      options:
        - "1.0.0"
        - "0.9.x"
        - "ุฃุฎุฑู (ูุฑุฌู ุงูุชุญุฏูุฏ ูู ุงูุณูุงู ุงูุฅุถุงูู)"
    validations:
      required: true

  - type: dropdown
    id: environment-node
    attributes:
      label: ุฅุตุฏุงุฑ Node.js
      description: ุฃู ุฅุตุฏุงุฑ ูู Node.js ุชุณุชุฎุฏูุ
      options:
        - "20.x"
        - "18.x"
        - "16.x"
        - "14.x"
        - "ุฃุฎุฑู (ูุฑุฌู ุงูุชุญุฏูุฏ ูู ุงูุณูุงู ุงูุฅุถุงูู)"
    validations:
      required: true

  - type: dropdown
    id: environment-platform
    attributes:
      label: ุงูููุตุฉ
      description: ุฃู ููุตุฉ ุชุนูู ุนูููุงุ
      options:
        - "ุฎุงุฏู Node.js"
        - "ูุชุตูุญ ุงูููุจ"
        - "React Native"
        - "Electron"
        - "ุฃุฎุฑู (ูุฑุฌู ุงูุชุญุฏูุฏ ูู ุงูุณูุงู ุงูุฅุถุงูู)"
    validations:
      required: true

  - type: dropdown
    id: environment-os
    attributes:
      label: ูุธุงู ุงูุชุดุบูู
      description: ุฃู ูุธุงู ุชุดุบูู ุชุณุชุฎุฏูุ
      options:
        - "Windows"
        - "macOS"
        - "Linux"
        - "ุฃุฎุฑู (ูุฑุฌู ุงูุชุญุฏูุฏ ูู ุงูุณูุงู ุงูุฅุถุงูู)"
    validations:
      required: true

  - type: dropdown
    id: calculation-method
    attributes:
      label: ุทุฑููุฉ ุงูุญุณุงุจ
      description: ุฃู ุทุฑููุฉ ุญุณุงุจ ููุช ุชุณุชุฎุฏูุ
      options:
        - "MWL (ุฑุงุจุทุฉ ุงูุนุงูู ุงูุฅุณูุงูู)"
        - "ISNA (ุงูุฌูุนูุฉ ุงูุฅุณูุงููุฉ ูุฃูุฑููุง ุงูุดูุงููุฉ)"
        - "Egypt (ุงูููุฆุฉ ุงููุตุฑูุฉ ุงูุนุงูุฉ ูููุณุงุญุฉ)"
        - "Makkah (ุฌุงูุนุฉ ุฃู ุงููุฑู)"
        - "Karachi (ุฌุงูุนุฉ ุงูุนููู ุงูุฅุณูุงููุฉ)"
        - "Custom (ูุฎุตุต)"
        - "ุทุฑู ูุชุนุฏุฏุฉ"
    validations:
      required: true

  - type: input
    id: coordinates
    attributes:
      label: ุงูุฅุญุฏุงุซูุงุช
      description: ุฎุท ุงูุนุฑุถ ูุงูุทูู ุญูุซ ุชุญุฏุซ ุงููุดููุฉ
      placeholder: "ุฎุท ุงูุนุฑุถ: 24.7136ุ ุฎุท ุงูุทูู: 46.6753"
    validations:
      required: true

  - type: input
    id: timezone
    attributes:
      label: ุงูููุทูุฉ ุงูุฒูููุฉ
      description: ุฅุฒุงุญุฉ ุงูููุทูุฉ ุงูุฒูููุฉ ุงููุณุชุฎุฏูุฉ
      placeholder: "3 (ูู UTC+3)"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: ุงูุณูุงู ุงูุฅุถุงูู
      description: |
        ุฃู ูุนูููุงุช ุฅุถุงููุฉ ูุฏ ุชุณุงุนุฏูุง ูู ููู ุงููุดููุฉ:
        - ููุทุงุช ุดุงุดุฉ ุฃู ุฑุณุงุฆู ุฎุทุฃ
        - ููุงุฑูุฉ ูุน ูุตุงุฏุฑ ููุงููุช ุงูุตูุงุฉ ุงูุฃุฎุฑู
        - ุงูุณูุงู ุงูุฅููููู ุฃู ุงูุซูุงูู
        - ุงููุถุงูุง ุฃู ุงูููุงูุดุงุช ุฐุงุช ุงูุตูุฉ
      placeholder: "ุฃุถู ุฃู ุณูุงู ุขุฎุฑ ุญูู ุงููุดููุฉ ููุง..."

  - type: dropdown
    id: severity
    attributes:
      label: ุงูุฎุทูุฑุฉ
      description: ูุง ูุฏู ุฎุทูุฑุฉ ูุฐู ุงููุดููุฉ ูุญุงูุฉ ุงูุงุณุชุฎุฏุงู ุงูุฎุงุตุฉ ุจูุ
      options:
        - "ุญุฑุฌุฉ - ุชููุน ุงููุธุงุฆู ุงูุฃุณุงุณูุฉ"
        - "ุนุงููุฉ - ุชุฃุซูุฑ ูุจูุฑ ุนูู ุงููุธุงุฆู"
        - "ูุชูุณุทุฉ - ุชุฃุซูุฑ ูุนุชุฏู"
        - "ููุฎูุถุฉ - ุฅุฒุนุงุฌ ุจุณูุท"
    validations:
      required: true

  - type: checkboxes
    id: willing-to-help
    attributes:
      label: ุงููุณุงููุฉ
      description: ูู ุชุฑุบุจ ูู ุงููุณุงุนุฏุฉ ูู ุฅุตูุงุญ ูุฐู ุงููุดููุฉุ
      options:
        - label: ุณุฃููู ูุณุชุนุฏุงู ูุชูุฏูู ุทูุจ ุณุญุจ ูุฅุตูุงุญ ูุฐู ุงููุดููุฉ
        - label: ูููููู ุงููุณุงุนุฏุฉ ูู ุงุฎุชุจุงุฑ ุงูุฅุตูุงุญุงุช ุงููุญุชููุฉ
        - label: ูููููู ุชูุฏูู ูุนูููุงุช ุฅุถุงููุฉ ุนูุฏ ุงูุญุงุฌุฉ