name: ๐ก ุทูุจ ููุฒุฉ
description: ุงูุชุฑุงุญ ููุฒุฉ ุฃู ุชุญุณูู ุฌุฏูุฏ
title: "[ููุฒุฉ]: "
labels: ["enhancement", "needs-discussion"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ุดูุฑุงู ูุงูุชุฑุงุญ ููุฒุฉ ุฌุฏูุฏุฉ! ูุฑุฌู ููุก ุงููููุฐุฌ ุฃุฏูุงู ููุณุงุนุฏุชูุง ูู ููู ุทูุจู.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: ุงููุชุทูุจุงุช ุงููุณุจูุฉ
      description: ูุฑุฌู ุชุฃููุฏ ูุง ููู ูุจู ุชูุฏูู ุทูุจ ุงูููุฒุฉ
      options:
        - label: ุจุญุซุช ุนู ุทูุจุงุช ุงูููุฒุงุช ุงูููุฌูุฏุฉ ุงูุชู ูุฏ ุชููู ูุดุงุจูุฉ
          required: true
        - label: ุฑุงุฌุนุช ุงูุชูุซูู ููุนุฑูุฉ ุฅุฐุง ูุงูุช ูุฐู ุงูููุฒุฉ ููุฌูุฏุฉ ุจุงููุนู
          required: true
        - label: ูุฐู ุงูููุฒุฉ ุชุชูุงุดู ูุน ุฃูุฏุงู ุงููุดุฑูุน (ุญุณุงุจุงุช ููุงููุช ุงูุตูุงุฉ ุจุฏูู ุฅูุชุฑูุช ูุจุฏูู ุงุนุชูุงุฏูุงุช)
          required: true

  - type: textarea
    id: summary
    attributes:
      label: ููุฎุต ุงูููุฒุฉ
      description: ูุตู ูุงุถุญ ูููุชุถุจ ููููุฒุฉ ุงูุชู ุชูุฏ ุฑุคูุชูุง
      placeholder: "ุฅุถุงูุฉ ุฏุนู ูุญุณุงุจ ุงุชุฌุงู ุงููุจูุฉ ุจูุงุกู ุนูู ุงูุฅุญุฏุงุซูุงุช..."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: ุจูุงู ุงููุดููุฉ
      description: ูุง ุงููุดููุฉ ุงูุชู ุชุญููุง ูุฐู ุงูููุฒุฉุ ูุง ุญุงูุฉ ุงูุงุณุชุฎุฏุงู ุงูุชู ุชุนุงูุฌูุงุ
      placeholder: |
        ุญุงููุงูุ ูุญุชุงุฌ ุงููุณุชุฎุฏููู ูุงุณุชุฎุฏุงู ููุชุจุงุช ูููุตูุฉ ููุญุตูู ุนูู ุงุชุฌุงู ุงููุจูุฉ.
        ุณูููู ูู ุงูููุงุณุจ ูุฌูุฏ ูุฐุง ุงูุญุณุงุจ ูู ููุณ ุงูููุชุจุฉ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: ุงูุญู ุงูููุชุฑุญ
      description: ุตู ุงูุญู ุงูุฐู ุชูุฏ ุฑุคูุชู ูููุฐุงู
      placeholder: |
        ุฅุถุงูุฉ ุทุฑููุฉ ุฌุฏูุฏุฉ `getQiblaDirection()` ุชุนูุฏ ุงูุงุชุฌุงู ุฅูู ููุฉ ูู ุงูุฅุญุฏุงุซูุงุช ุงููุนุทุงุฉ...
    validations:
      required: true

  - type: textarea
    id: api-design
    attributes:
      label: ุชุตููู ุงููุงุฌูุฉ ุงูุจุฑูุฌูุฉ ุงูููุชุฑุญ
      description: ุฅู ุฃูููุ ุตู ููู ุชุชุตูุฑ ุงููุงุฌูุฉ ุงูุจุฑูุฌูุฉ ููุฐู ุงูููุฒุฉ
      render: typescript
      placeholder: |
        // ูุซุงู ุชุตููู ุงููุงุฌูุฉ ุงูุจุฑูุฌูุฉ
        const sdk = new PrayerTimesSDK(lat, lng, date, timezone, options);

        // ุทุฑููุฉ ุฌุฏูุฏุฉ
        const qiblaDirection = sdk.getQiblaDirection();
        // ุชุนูุฏ: { bearing: 245.3, direction: "WSW" }

        // ุฃู ูุฌุฒุก ูู ุงูุงุณุชุฌุงุจุฉ ุงูููุฌูุฏุฉ
        const times = sdk.getTimes();
        // ุชุนูุฏ: { fajr: "05:30", ..., qibla: { bearing: 245.3 } }

  - type: dropdown
    id: feature-type
    attributes:
      label: ููุน ุงูููุฒุฉ
      description: ูุง ููุน ูุฐู ุงูููุฒุฉุ
      options:
        - "ุทุฑููุฉ ุญุณุงุจ ุฌุฏูุฏุฉ"
        - "ููุช ุตูุงุฉ ุฅุถุงูู (ูุซู ุงูุชูุฌุฏุ ุงูุฅุดุฑุงู)"
        - "ุชุญุณูู ุชูุณูู ุงูุฅุฎุฑุงุฌ"
        - "ุชุญุณูู ุงูุฃุฏุงุก"
        - "ุชุญุณูู ุชุฌุฑุจุฉ ุงููุทูุฑ"
        - "ุชุญุณูู ุงูุชูุซูู"
        - "ุชุญุณูู ุงูุงุฎุชุจุงุฑ"
        - "ุฃุฎุฑู (ูุฑุฌู ุงูุชุญุฏูุฏ ูู ุงูุชูุงุตูู)"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: ุงูุฃููููุฉ
      description: ูุง ูุฏู ุฃูููุฉ ูุฐู ุงูููุฒุฉ ุจุงููุณุจุฉ ููุ
      options:
        - "ุนุงููุฉ - ุฃุณุงุณูุฉ ูุญุงูุฉ ุงูุงุณุชุฎุฏุงู ุงูุฎุงุตุฉ ุจู"
        - "ูุชูุณุทุฉ - ุณุชููู ูููุฏุฉ ุฌุฏุงู"
        - "ููุฎูุถุฉ - ูุทููุฉ ุฃู ุชููู ููุฌูุฏุฉ"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: ุงูุจุฏุงุฆู ุงููุนุชุจุฑุฉ
      description: ูู ุงุนุชุจุฑุช ุฃู ุญููู ุจุฏููุฉ ุฃู ุทุฑู ุงูุชูุงูุ
      placeholder: |
        ุฃุณุชุฎุฏู ุญุงููุงู ููุชุจุฉ ูููุตูุฉ X ููุฐู ุงููุธููุฉ...
        ุงุนุชุจุฑุช ุชูููุฐูุง ุจููุณู ููู ุฃูุถู ุฃู ุชููู ูู ุงูููุชุจุฉ ุงูุฑุฆูุณูุฉ...

  - type: textarea
    id: use-cases
    attributes:
      label: ุญุงูุงุช ุงูุงุณุชุฎุฏุงู
      description: ุตู ุณููุงุฑูููุงุช ูุญุฏุฏุฉ ุญูุซ ุณุชููู ูุฐู ุงูููุฒุฉ ูููุฏุฉ
      placeholder: |
        1. ุชุทุจูู ุตูุงุฉ ููุฌูุงู ูุนุฑุถ ููุงููุช ุงูุตูุงุฉ ูุงุชุฌุงู ุงููุจูุฉ
        2. ูููุน ูุณุฌุฏ ูุนุฑุถ ูุนูููุงุช ุฅุณูุงููุฉ ูุงููุฉ
        3. ุชุทุจูู ุณูุฑ ูููุณูููู ุงูุฐูู ูุฒูุฑูู ูุฏู ุฌุฏูุฏุฉ
    validations:
      required: true

  - type: checkboxes
    id: compatibility
    attributes:
      label: ูุชุทูุจุงุช ุงูุชูุงูู
      description: ุฃู ููุตุงุช ูุฌุจ ุฃู ุชุฏุนู ูุฐู ุงูููุฒุฉุ
      options:
        - label: ูุชุตูุญุงุช ุงูููุจ
        - label: ุฎุงุฏู Node.js
        - label: React Native
        - label: ุชุทุจููุงุช Electron
        - label: ุฌููุน ุงูููุตุงุช (ููุถู)

  - type: textarea
    id: implementation-notes
    attributes:
      label: ุงุนุชุจุงุฑุงุช ุงูุชูููุฐ
      description: ุฃู ุงุนุชุจุงุฑุงุช ุชูููุฉ ุฃู ูููุฏ ุฃู ุงูุชุฑุงุญุงุช ููุชูููุฐ
      placeholder: |
        - ูุฌุจ ุงูุญูุงุธ ุนูู ูุชุทูุจ ุนุฏู ุงูุงุนุชูุงุฏูุงุช ุงูุฎุงุฑุฌูุฉ
        - ูุฌุจ ุฃูุง ุชุฒูุฏ ุญุฌู ุงูุญุฒูุฉ ุจุดูู ูุจูุฑ
        - ูุฌุจ ุงุชุจุงุน ุฃููุงุท ุงููุงุฌูุฉ ุงูุจุฑูุฌูุฉ ุงูููุฌูุฏุฉ
        - ุงุนุชุจุงุฑ ุขุซุงุฑ ุงูุฃุฏุงุก

  - type: textarea
    id: examples
    attributes:
      label: ุฃูุซูุฉ ุฃู ูุฑุงุฌุน
      description: |
        ูุฏู ุฃูุซูุฉ ุนูู ููุฒุงุช ูุดุงุจูุฉ ูู ููุชุจุงุช ุฃุฎุฑูุ ุฃู ุฎูุงุฑุฒููุงุชุ ุฃู ุชูููุฐุงุช ูุฑุฌุนูุฉ
      placeholder: |
        ูุดุงุจู ููููุฒุฉ ูู ููุชุจุฉ X: [ุฑุงุจุท]
        ูุฑุฌุน ุงูุฎูุงุฑุฒููุฉ: [ุฑุงุจุท]
        ูุตุฏุฑ ุงูุณูุทุฉ ุงูุฅุณูุงููุฉ: [ุฑุงุจุท]

  - type: dropdown
    id: breaking-change
    attributes:
      label: ุชุบููุฑ ูุงุณุฑ
      description: ูู ุณุชุชุทูุจ ูุฐู ุงูููุฒุฉ ุชุบููุฑุงุช ูุงุณุฑุฉ ูููุงุฌูุฉ ุงูุจุฑูุฌูุฉ ุงูููุฌูุฏุฉุ
      options:
        - "ูุง - ุฅุถุงููุฉ ููุท"
        - "ูุนู - ุชุบููุฑุงุช ูุงุณุฑุฉ ุทูููุฉ"
        - "ูุนู - ุชุบููุฑุงุช ูุงุณุฑุฉ ูุจูุฑุฉ"
        - "ุบูุฑ ูุชุฃูุฏ"
    validations:
      required: true

  - type: checkboxes
    id: contribution-intent
    attributes:
      label: ุงููุณุงููุฉ
      description: ูู ุชุฑุบุจ ูู ุงููุณุงุนุฏุฉ ูู ุชูููุฐ ูุฐู ุงูููุฒุฉุ
      options:
        - label: ุณุฃููู ูุณุชุนุฏุงู ูุชูููุฐ ูุฐู ุงูููุฒุฉ ุจููุณู
        - label: ูููููู ุงููุณุงุนุฏุฉ ูู ุงูุจุญุซ ูุงูุงุฎุชุจุงุฑ
        - label: ูููููู ุชูุฏูู ุฎุจุฑุฉ ูู ุงููุฌุงู (ุงูููู ุงูุฅุณูุงููุ ุงููููุ ุฅูุฎ)
        - label: ูููููู ุงููุณุงุนุฏุฉ ูู ุงูุชูุซูู ูุงูุฃูุซูุฉ
        - label: ูููููู ุงููุณุงุนุฏุฉ ูู ุงูุงุฎุชุจุงุฑ ุนุจุฑ ููุตุงุช ูุฎุชููุฉ

  - type: textarea
    id: additional-context
    attributes:
      label: ุงูุณูุงู ุงูุฅุถุงูู
      description: |
        ุฃู ูุนูููุงุช ุฅุถุงููุฉ ูุฏ ุชููู ูููุฏุฉ:
        - ููุทุงุช ุดุงุดุฉ ุฃู ููุงุฐุฌ ุฃูููุฉ
        - ุฑูุงุจุท ูุณูุทุงุช ุฅุณูุงููุฉ ุฐุงุช ุตูุฉ ุฃู ูุตุงุฏุฑ
        - ุงุนุชุจุงุฑุงุช ุฅูููููุฉ ุฃู ุซูุงููุฉ
        - ูุชุทูุจุงุช ุงูุฃุฏุงุก
      placeholder: "ุฃุถู ุฃู ุณูุงู ุขุฎุฑ ุญูู ุทูุจ ุงูููุฒุฉ ููุง..."

  - type: textarea
    id: islamic-context
    attributes:
      label: ุงูุณูุงู ุงูุฅุณูุงูู (ุฅู ุฃููู)
      description: ุฅุฐุง ูุงู ุทูุจ ุงูููุฒุฉ ูุชุนูู ุจุฌูุงูุจ ุฏูููุฉ ุฃู ููููุฉ
      placeholder: |
        - ูุฑุงุฌุน ูู ุงูุณูุทุงุช ุงูุฅุณูุงููุฉ
        - ุงุฎุชูุงูุงุช ุงููุฐุงูุจ ุงูููููุฉ
        - ุงุนุชุจุงุฑุงุช ุฅูููููุฉ ุฃู ุซูุงููุฉ
        - ูุตุงุฏุฑ ุงููุชุงูู ุฃู ุงูุฃุญูุงู ุงูุดุฑุนูุฉ